#!/bin/bash

# ccache
export USE_CCACHE=1
export CCACHE_DIR=/home/ccache/neroprebuilts/misc/linux-x86/ccache/ccache -M 50G
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export KBUILD_BUILD_USER=Nero
export KBUILD_BUILD_HOST=SpeedHorn

# clean
make clean && make clobber

# build
. build/envsetup.sh
lunch rom_device-userdebug
make bacon -j8
